-- Kiểm tra cấu trúc bảng stations hiện tại
SELECT COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'stations'
ORDER BY ORDINAL_POSITION;

-- Kiểm tra cấu trúc bảng vehicle_models hiện tại
SELECT COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'vehicle_models'
ORDER BY ORDINAL_POSITION;

-- Kiểm tra cấu trúc bảng vehicles hiện tại
SELECT COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'vehicles'
ORDER BY ORDINAL_POSITION;
